spring:
  application:
    name: backend-service
  cloud:
    consul:
      discovery:
        instanceId: backend-service
        name: bbc

server:
  port: 8090

management:
  security:
    enabled: false